### PR TITLE
Responsive design giraudremi92 branch

### PR DESCRIPTION
**Pull request by giraudremi92**
Add the Responsive behavior for Laptop screen, Tablet and mobile.
With some changes in CSS and React components
As described here : Add responsive behavior #19
https://github.com/Pyrrha-Platform/Pyrrha-Website/issues/19

**Is this related to an open issue?**
https://github.com/Pyrrha-Platform/Pyrrha-Website/issues/19

+++ Website ReadMe Review #17
Add Yarn install in the Readme File
https://github.com/Pyrrha-Platform/Pyrrha-Website/issues/17

### CODE REVIEW

**Comment by krook** [comment]
Thank you @giraudremi92! 

I still see some issues when I resize in Chrome or test the mobile/tablet views. But those are things we can iterate on to improve. Merging.

**Comment by giraudremi92** [comment]
@krook 
Ok let me know the issues then i could maybe resolve them
Thank you

**Comment by krook** [comment]
Very strange. When I built and ran your fork locally, it seemed like it still had some of the same issues as in production, but when I merged and it pushed a build to https://pyrrha-platform.org/ it shows correctly. 

So, very nice job! It looks great.

**Comment by giraudremi92** [comment]
Cool ! Thank you !
Indeed i didn't try to build it locally , i just tested it in serve mode so I can't tell.
With Js Framework sometimes it's hard to see the build version locally maybe your http local server or your cache  ?
Ps : I guess the project is using Flask and I know pretty well this Backend Framework if you have some issues please let me know I ll glad to help ;)

**Pull request merged**
